# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    "concat": "https://github.com/puppetlabs/puppetlabs-concat"
    "cron_core": "https://github.com/puppetlabs/puppetlabs-cron_core.git"
    "facts": "https://github.com/puppetlabs/puppetlabs-facts.git"
    "inifile": "https://github.com/puppetlabs/puppetlabs-inifile"
    "openssl": "https://github.com/camptocamp/puppet-openssl.git"
    "provision": "https://github.com/puppetlabs/provision.git"
    "puppet_agent": "https://github.com/puppetlabs/puppetlabs-puppet_agent.git"
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib"
